### ISSUE TITLE
ILIAS 7 compatibility unclear

### ISSUE THREAD

**Issue by colin-kiegel** [srsolutionsag/SrVideoInterview#1]
README.md says it's compatible with ILIAS 7
plugin.php says only ILIAS 6

**Comment by chfsx** [comment]
This may be an Issue in the README, we will update that accordingly. The relevant value is in plugin.php

**Comment by chfsx** [comment]
Now I see, the README says ILIAS 6 as well, it's PHP >= 7 you maybe saw.
